package Qcalc;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();

        calc.add(1, 2);
	    calc.subtract(2, 4);
	    calc.multiply(2, 6);
	    calc.divide(10, 5);

        System.out.println(calc.getResult());
    }
}




